language: ruby
rvm: 1.8.7
before_install:
  - gem update --system 1.6.2 # Downgrade to the same version installed on the server
  - gem --version
jobs:
  include:
    - stage: test
      script: make test_postcodes
