dist: trusty
language: ruby
rvm: 2.2.3
jobs:
  include:
    - stage: test
      script: bundle exec rake
      name: Run code tests
    - script: bundle exec ./postcodes.rb --test
      name: Test postcodes.csv
    - script: bundle exec ./parse-members.rb --test
      name: Test members datafiles
